### ISSUE TITLE
How to install a package that Criann doesn't have?

### ISSUE THREAD

**Issue by jizhang02** [jajupmochi/how-to-use-criann-cluster#1]
Hello,
I want to install [ANTs](https://github.com/ANTsX/ANTs) (which has many python files)
on the Criann, and at the same time, I have to add the location of the ANTs binaries to the PATH environmental variable. Is that possible? Should I intall them on my own space or else? Because every time when I run the program on the server, in other words, when I submit the job to the server, I have to call the functions of ANTs. So I don't know where the ANTs should be installed?
Thank you. Looking forward to your reply.

**Comment by jajupmochi** [comment]
Yes it is possible. Check [this](https://github.com/jajupmochi/how-to-use-criann-cluster/blob/master/README.md#how-to-install-a-python-package-that-doesnt-exist-on-criann-server-triangular_flag_on_post) for example.

You can install everything in your own directory, and then add the PATH to the local `.bashrc` or `.bash_profile` file. (I do not remember which would work, you can try both.) If the file does not exist, simply create one. Notice these files are in your local root path (a.k.a, the `~` directory). Add the path like this:
`PATH=$HOME/installed/gcc-7.4.0/bin:$PATH`
`export PATH`

You may also need to install some other related packages, add their paths. Just follow the messages when you get an error. 

When you submit a job to the server, the server will automatically load every package and setting from your local directory, just as how it loads codes and datasets from your local directory. So do not worry about that, just make sure everything needed is properly set.

Check also [Compiling ANTs on Linux and Mac OS](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS) for details.

**Comment by jizhang02** [comment]
Hello, jajupmochi,
Thank you for your answer!
When I tried to install a Python package, there is an error.
It seems no pip command.
![image](https://user-images.githubusercontent.com/46089068/68786097-7ee71080-063f-11ea-8ece-5cd1d9ab05b2.png)

**Comment by jajupmochi** [comment]
You may not have pip/pip3 installed.

You can try this command first:
`python3 -m pip install --user tables`

If it does not work either, you may need to install pip/pip3 manually from source.

You can follow the instruction on [this](https://pip.pypa.io/en/stable/installing/) this site.

**Comment by jizhang02** [comment]
Hello, yes! you are right!
I don't have pip command, so I use this sentence to download the get-pip.py file:
`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
Then I run this python file by :
`python get-pip.py`
Now, pip was successfully installed, but not in the system environment variable, so I need to add the path of pip into system path by:
`vim ~/.bashrc`
`export PATH=path1:path2:pippath`
After saving the .bashrc, I can use this command to make it effective immediately:
`source ~/.bashrc`
Now, I can use pip command to install python packages, attention, you have to add `--user`, or you could fail according to my experience.
`pip install tables --user`

Thank you very much!

**Comment by jizhang02** [comment]
After one year, finally, I understand how Criann works. If you want to install a package. There are some steps:
1. Open corresponding module. For example, when you use python3 and deep learning framework.
`module load python3/3.6.1_dl`
2. Install the packages. To get permission, remember to add a `--user` command.
`pip install segmentation-models==1.0.1 --user`
Make sure you have enough space to install your packages. If not, delete some files. Otherwise, there will be errors like:
`ERROR: Could not install packages due to an EnvironmentError: [Errno 122] Disk quota exceeded`
That's all. Hope to help you.☺
